"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const enquiryTypes = ["International market development", "Manufacturer representation", "Customer and partner identification", "Distributor or system-integrator development", "Technology sourcing", "Technical & Commercial Coordination", "Payment-technology opportunities", "Retail or self-service technology opportunities"];
const briefing = ["Your company and technology", "The product or solution involved", "The market being considered", "The customer, channel, supplier, or partner being sought", "The current commercial situation", "The type of support required"];
function Arrow(){return <span aria-hidden="true">↗</span>;} function Wordmark(){return <span className="wordmark-text">NELVA</span>;}

export default function ContactPage(){
  const [menuOpen,setMenuOpen]=useState(false); const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>20);const onKey=(e:KeyboardEvent)=>e.key==="Escape"&&setMenuOpen(false);onScroll();window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("keydown",onKey);return()=>{window.removeEventListener("scroll",onScroll);window.removeEventListener("keydown",onKey);};},[]);
  useEffect(()=>{document.body.style.overflow=menuOpen?"hidden":"";return()=>{document.body.style.overflow="";};},[menuOpen]);
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className={`site-header ${scrolled?"is-scrolled":""}`}><div className="shell header-inner"><Link className="wordmark" href="/"><Wordmark /></Link><nav className="desktop-nav" aria-label="Primary navigation"><a href="/company">Company</a><a href="/capabilities">Capabilities</a><a href="/industries">Industries</a><a href="/contact" aria-current="page">Contact</a><a className="header-cta" href="#contact-details">Discuss your market objectives <Arrow /></a></nav><button className="menu-button" type="button" aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={()=>setMenuOpen(v=>!v)}><span>{menuOpen?"Close":"Menu"}</span><span className="menu-symbol" aria-hidden="true">{menuOpen?"×":"+"}</span></button></div><div id="mobile-menu" className={`mobile-menu ${menuOpen?"is-open":""}`} aria-hidden={!menuOpen}><nav className="shell mobile-nav">{[["Company","/company"],["Capabilities","/capabilities"],["Industries","/industries"],["Contact","/contact"]].map(([l,h],i)=><a href={h} key={l} aria-current={l==="Contact"?"page":undefined} onClick={()=>setMenuOpen(false)}><span className="mobile-nav-index">0{i+1}</span><span>{l}</span><Arrow /></a>)}</nav><div className="shell mobile-menu-meta"><span>Espoo, Finland</span><span>Business ID 3574517-6</span></div></div></header>
    <main id="main">
      <section className="contact-page-hero shell" aria-labelledby="contact-title"><div className="contact-page-meta"><span><i className="signal-dot" /> Contact</span><span>Begin with the objective</span></div><div className="contact-page-grid"><h1 id="contact-title">Start with the market objective.</h1><p>Tell Nelva about the product, partnership, representation requirement, or commercial opportunity you would like to discuss. A short introduction is enough to begin.</p></div><a className="contact-down" href="#prepare"><span>Prepare your enquiry</span><i>↓</i></a></section>
      <section id="prepare" className="contact-prepare section-space" aria-labelledby="prepare-title"><div className="shell grid-12"><div className="section-index"><span>01</span><span>What to include</span></div><div className="section-content"><div className="heading-pair"><h2 id="prepare-title">Useful context for an initial conversation.</h2><p>Confidential information is not required at this stage. Share only enough context to understand the technology and commercial objective.</p></div><ol className="briefing-list">{briefing.map((item,i)=><li key={item}><span>0{i+1}</span><strong>{item}</strong></li>)}</ol></div></div></section>
      <section className="enquiry-types section-space" aria-labelledby="enquiries-title"><div className="shell grid-12"><div className="section-index"><span>02</span><span>Relevant enquiries</span></div><div className="section-content"><h2 id="enquiries-title">Where the conversation may begin.</h2><div className="enquiry-grid">{enquiryTypes.map((item,i)=><span key={item}><i>{String(i+1).padStart(2,"0")}</i>{item}</span>)}</div></div></div></section>
      <section id="contact-details" className="official-contact section-space" aria-labelledby="official-title"><div className="shell official-grid"><div className="official-label"><span>03</span><span>Official contact</span><strong>ESPOO<br />FINLAND</strong></div><div className="official-content"><p className="eyebrow">Business enquiries</p><h2 id="official-title">A verified business channel will be published here.</h2><p>Nelva will publish its official contact address only after the mailbox has been created and externally tested. No unverified email address or non-functional enquiry form is shown.</p><div className="corporate-card"><span>Corporate information</span><strong>Nelva</strong><p>Espoo, Finland<br />Business ID: 3574517-6<br />nelvaglobal.com</p></div></div></div></section>
      <section className="contact-boundary section-space"><div className="shell"><span>Commercial clarification</span><p>Submitting an enquiry or beginning a discussion does not create a representation, agency, exclusivity, or other commercial agreement. Any engagement and authority must be confirmed separately in writing.</p></div></section>
    </main>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><Link className="wordmark footer-wordmark" href="/"><Wordmark /></Link><p>International market development for technology manufacturers.</p></div><nav className="footer-column" aria-label="Footer navigation"><span className="footer-label">Navigate</span><a href="/company">Company</a><a href="/capabilities">Capabilities</a><a href="/industries">Industries</a><a href="/contact">Contact</a></nav><div className="footer-column"><span className="footer-label">Corporate</span><span>Nelva</span><span>Espoo, Finland</span><span>Business ID: 3574517-6</span><span>nelvaglobal.com</span></div><div className="footer-end"><span>© 2026 Nelva</span><a href="#main">Back to top ↑</a></div></div></footer>
  </>;
}
